app:
  admin:
    email: ${ADMIN_EMAIL:admin@gemara.com}
    password: ${ADMIN_PASSWORD:}

  cart:
    tax-rate: ${CART_TAX_RATE:0.10}
    shipping-threshold: ${CART_SHIPPING_THRESHOLD:1000}
    standard-shipping-fee: ${CART_STANDARD_SHIPPING_FEE:50}
    gift-wrap-fee: ${CART_GIFT_WRAP_FEE:5}

spring:
  application:
    name: jewelry-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:jewelry_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:user@example.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    jwt:
      secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration-ms: 86400000 # 24 hours
