import { join } from 'node:path';
import { existsSync } from 'node:fs';
import {
  AngularNodeAppEngine,
  createNodeRequestHandler,
  isMainModule,
  writeResponseToNodeResponse,
} from '@angular/ssr/node';
import express from 'express';

const serverDistFolder = import.meta.dirname;
const browserDistFolder = join(serverDistFolder, '../browser');

// Verify the required directories exist
if (!existsSync(browserDistFolder)) {
  console.error(`ERROR: Browser distribution folder not found at ${browserDistFolder}`);
  console.error('Make sure the Angular application has been built with: npm run build -- --configuration production');
  process.exit(1);
}

let reqHandlerExport: any = null;

// Async initialization wrapped in IIFE to avoid top-level await
(async () => {
  try {
    // Load manifests before creating the engine
    // These files are generated by Angular build and exist only at runtime
    console.log('Loading Angular SSR manifests...');
    
    const appEngineManifestPath = join(serverDistFolder, 'angular-app-engine-manifest.mjs');
    if (existsSync(appEngineManifestPath)) {
      // @ts-ignore - File exists at runtime but not at compile time
      await import('./angular-app-engine-manifest.mjs');
      console.log('✓ App engine manifest loaded');
    }

    const appManifestPath = join(serverDistFolder, 'angular-app-manifest.mjs');
    if (existsSync(appManifestPath)) {
      // @ts-ignore - File exists at runtime but not at compile time
      await import('./angular-app-manifest.mjs');
      console.log('✓ App manifest loaded');
    }

    const app = express();
    const angularApp = new AngularNodeAppEngine();

    console.log('✓ AngularNodeAppEngine initialized');

    /**
     * Serve static files from /browser
     */
    app.use(
      express.static(browserDistFolder, {
        maxAge: '1y',
        index: false,
        redirect: false,
      }),
    );

    /**
     * Handle all other requests by rendering the Angular application.
     */
    app.use((req, res, next) => {
      angularApp
        .handle(req)
        .then((response) =>
          response ? writeResponseToNodeResponse(response, res) : next(),
        )
        .catch(next);
    });

    // Store the request handler for export
    reqHandlerExport = createNodeRequestHandler(app);

    /**
     * Start the server if this module is the main entry point, or it is ran via PM2.
     * The server listens on the port defined by the `PORT` environment variable, or defaults to 4000.
     */
    if (isMainModule(import.meta.url) || process.env['pm_id']) {
      const port = process.env['PORT'] || 4000;
      app.listen(port, (error) => {
        if (error) {
          throw error;
        }

        console.log(`Node Express server listening on http://localhost:${port}`);
      });
    }

  } catch (error: any) {
    console.error('ERROR: Failed to initialize Angular SSR application');
    console.error('Details:', error.message);
    if (error.stack) {
      console.error('Stack:', error.stack);
    }
    process.exit(1);
  }
})();

/**
 * Request handler used by the Angular CLI (for dev-server and during build) or Firebase Cloud Functions.
 * @ts-ignore - Will be set during async initialization
 */
export const reqHandler = reqHandlerExport;
